// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcAJBd0UJLFWYlMNU19wep6TR8P66U7pQ',
    appId: '1:303264154880:android:0d94978eda0cc6d35c1fe5',
    messagingSenderId: '303264154880',
    projectId: 'skylab-mobile',
    storageBucket: 'skylab-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUX5B8IlsYBX53RcNkF4XjpsObKvqnJl8',
    appId: '1:303264154880:ios:f0be65e5414b689d5c1fe5',
    messagingSenderId: '303264154880',
    projectId: 'skylab-mobile',
    storageBucket: 'skylab-mobile.firebasestorage.app',
    androidClientId: '303264154880-riersu5feqqukbbq1o7u12fsvj7ard3n.apps.googleusercontent.com',
    iosClientId: '303264154880-ei0i0vsmeih0lukoi1f58ui2iep6t1ri.apps.googleusercontent.com',
    iosBundleId: 'fr.skylabs.mobile.skylabMobile',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK0M3sPn9ALE1Gmnl9T-rGyK2QMt-3-lw',
    appId: '1:303264154880:web:47eff60a1a51c15a5c1fe5',
    messagingSenderId: '303264154880',
    projectId: 'skylab-mobile',
    authDomain: 'skylab-mobile.firebaseapp.com',
    storageBucket: 'skylab-mobile.firebasestorage.app',
  );

}